### ISSUE TITLE
can't get config.json to be identified

### ISSUE THREAD

**Issue by ntzb** [free-bots/AriaNg#1]
hi, I very much appreciate you implementing what I think are missing features, such as a static config, so all of my lan users can connect without each setting up settings in their browser.

I can't get it to work though. on v1.2.6
I saved the settings, exported the file, renamed it to config.json and put in the root directory, next to the index.html file, but it's not getting recognized - the default settings (with dracula theme) are there.
is there something else I need to do?

**Comment by free-bots** [comment]
Hi, sorry for the late response. I wonder if notifications were turned off. 
If you change something and you reload the current tab changes get ignored due to the fact that i found no better solution than fetching the config an reload the page once a value in session storage is not present . You can clear the session storage or open the page in an other tap every time you change something. 
![storage](https://user-images.githubusercontent.com/54210595/174473537-7497687d-e17f-4692-815b-9a11d0b4dc27.png)

**Comment by free-bots** [comment]
@ntzb please let me know if this issue still exists. Otherwise this issue will be closed soon due to inactivity.

**Comment by ntzb** [comment]
@free-bots I think I wasn't clear.
how do I use the config.json that I created?
this is the dir structure as of now:
![2022-10-07__18-38-51](https://user-images.githubusercontent.com/1606302/194593535-8b72f216-c8ad-49b0-93bc-d804d8fe43c8.jpeg)

when I open "index.html" in my browser, I don't see the configuration that is saved in config.json.
am I doing something wrong?

**Comment by free-bots** [comment]
@ntzb you did everything right with adding config.json to root. I think i could reproduce your issue. My browser keeps deleting page data opening a new tab shows me the config every time. Onced i changed the browser the config was not loaded. 

Could you try version [1.3.1](https://github.com/free-bots/AriaNg/releases/tag/1.3.1) it includes a fix for it ? 
After a config change open the page in a new tab and your changes should be visible.

**Comment by free-bots** [comment]
@ntzb i think i got your point. You don't use any http server right? This is not supported the browser blocks file acces via javascript.  But you can use one of these tools to run it localy: 

https://formulae.brew.sh/formula/darkhttpd -> open the terminal in your folder and run darkhttpd ./ --port 8080
https://github.com/vercel/serve#readme -> open the terminal in your folder and run serve ./
https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer -> open the folder with vscode on click on go live

**Comment by ntzb** [comment]
@free-bots sorry, I wasn't aware that the browser doesn't pick up the config.json file (cors stuff?).
I do have an nginx server running the mayswind/AriaNg version, but I just wanted to try yours with a regular browser before I replaced it.

it works as expected, so I'm closing this.
thanks for your help!
